[gee]
project_id = "your-gee-project-id"
drive_folder = "GEE_Exports"

[paths]
download_folder_local = "./downloads"
cache_folder = "./.cache/"

[defaults]
default_satellite = "MODIS_MOD13Q1_061"
default_method = "Drive"
default_reducer = "mean"
